// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.1
// source: internal/grpc/proto/orchestrator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Orchestrator_CreateSandbox_FullMethodName    = "/orchestrator.Orchestrator/CreateSandbox"
	Orchestrator_DestroySandbox_FullMethodName   = "/orchestrator.Orchestrator/DestroySandbox"
	Orchestrator_GetSandboxStatus_FullMethodName = "/orchestrator.Orchestrator/GetSandboxStatus"
	Orchestrator_ExecStream_FullMethodName       = "/orchestrator.Orchestrator/ExecStream"
	Orchestrator_ValidateQuiz_FullMethodName     = "/orchestrator.Orchestrator/ValidateQuiz"
	Orchestrator_WatchResources_FullMethodName   = "/orchestrator.Orchestrator/WatchResources"
)

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorClient interface {
	// Sandbox lifecycle
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error)
	DestroySandbox(ctx context.Context, in *DestroySandboxRequest, opts ...grpc.CallOption) (*Empty, error)
	GetSandboxStatus(ctx context.Context, in *GetSandboxStatusRequest, opts ...grpc.CallOption) (*SandboxStatus, error)
	// Terminal exec — bidirectional stream
	ExecStream(ctx context.Context, opts ...grpc.CallOption) (Orchestrator_ExecStreamClient, error)
	// Validation
	ValidateQuiz(ctx context.Context, in *ValidateQuizRequest, opts ...grpc.CallOption) (*ValidateQuizResponse, error)
	// Sandbox resource state — server-side stream for real-time updates
	WatchResources(ctx context.Context, in *WatchResourcesRequest, opts ...grpc.CallOption) (Orchestrator_WatchResourcesClient, error)
}

type orchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorClient(cc grpc.ClientConnInterface) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error) {
	out := new(CreateSandboxResponse)
	err := c.cc.Invoke(ctx, Orchestrator_CreateSandbox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) DestroySandbox(ctx context.Context, in *DestroySandboxRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Orchestrator_DestroySandbox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) GetSandboxStatus(ctx context.Context, in *GetSandboxStatusRequest, opts ...grpc.CallOption) (*SandboxStatus, error) {
	out := new(SandboxStatus)
	err := c.cc.Invoke(ctx, Orchestrator_GetSandboxStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) ExecStream(ctx context.Context, opts ...grpc.CallOption) (Orchestrator_ExecStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Orchestrator_ServiceDesc.Streams[0], Orchestrator_ExecStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &orchestratorExecStreamClient{stream}
	return x, nil
}

type Orchestrator_ExecStreamClient interface {
	Send(*ExecInput) error
	Recv() (*ExecOutput, error)
	grpc.ClientStream
}

type orchestratorExecStreamClient struct {
	grpc.ClientStream
}

func (x *orchestratorExecStreamClient) Send(m *ExecInput) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orchestratorExecStreamClient) Recv() (*ExecOutput, error) {
	m := new(ExecOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orchestratorClient) ValidateQuiz(ctx context.Context, in *ValidateQuizRequest, opts ...grpc.CallOption) (*ValidateQuizResponse, error) {
	out := new(ValidateQuizResponse)
	err := c.cc.Invoke(ctx, Orchestrator_ValidateQuiz_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) WatchResources(ctx context.Context, in *WatchResourcesRequest, opts ...grpc.CallOption) (Orchestrator_WatchResourcesClient, error) {
	stream, err := c.cc.NewStream(ctx, &Orchestrator_ServiceDesc.Streams[1], Orchestrator_WatchResources_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &orchestratorWatchResourcesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Orchestrator_WatchResourcesClient interface {
	Recv() (*ResourceEvent, error)
	grpc.ClientStream
}

type orchestratorWatchResourcesClient struct {
	grpc.ClientStream
}

func (x *orchestratorWatchResourcesClient) Recv() (*ResourceEvent, error) {
	m := new(ResourceEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrchestratorServer is the server API for Orchestrator service.
// All implementations must embed UnimplementedOrchestratorServer
// for forward compatibility
type OrchestratorServer interface {
	// Sandbox lifecycle
	CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error)
	DestroySandbox(context.Context, *DestroySandboxRequest) (*Empty, error)
	GetSandboxStatus(context.Context, *GetSandboxStatusRequest) (*SandboxStatus, error)
	// Terminal exec — bidirectional stream
	ExecStream(Orchestrator_ExecStreamServer) error
	// Validation
	ValidateQuiz(context.Context, *ValidateQuizRequest) (*ValidateQuizResponse, error)
	// Sandbox resource state — server-side stream for real-time updates
	WatchResources(*WatchResourcesRequest, Orchestrator_WatchResourcesServer) error
	mustEmbedUnimplementedOrchestratorServer()
}

// UnimplementedOrchestratorServer must be embedded to have forward compatible implementations.
type UnimplementedOrchestratorServer struct {
}

func (UnimplementedOrchestratorServer) CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedOrchestratorServer) DestroySandbox(context.Context, *DestroySandboxRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroySandbox not implemented")
}
func (UnimplementedOrchestratorServer) GetSandboxStatus(context.Context, *GetSandboxStatusRequest) (*SandboxStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSandboxStatus not implemented")
}
func (UnimplementedOrchestratorServer) ExecStream(Orchestrator_ExecStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecStream not implemented")
}
func (UnimplementedOrchestratorServer) ValidateQuiz(context.Context, *ValidateQuizRequest) (*ValidateQuizResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateQuiz not implemented")
}
func (UnimplementedOrchestratorServer) WatchResources(*WatchResourcesRequest, Orchestrator_WatchResourcesServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchResources not implemented")
}
func (UnimplementedOrchestratorServer) mustEmbedUnimplementedOrchestratorServer() {}

// UnsafeOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServer will
// result in compilation errors.
type UnsafeOrchestratorServer interface {
	mustEmbedUnimplementedOrchestratorServer()
}

func RegisterOrchestratorServer(s grpc.ServiceRegistrar, srv OrchestratorServer) {
	s.RegisterService(&Orchestrator_ServiceDesc, srv)
}

func _Orchestrator_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_DestroySandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).DestroySandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_DestroySandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).DestroySandbox(ctx, req.(*DestroySandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_GetSandboxStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetSandboxStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_GetSandboxStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetSandboxStatus(ctx, req.(*GetSandboxStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_ExecStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrchestratorServer).ExecStream(&orchestratorExecStreamServer{stream})
}

type Orchestrator_ExecStreamServer interface {
	Send(*ExecOutput) error
	Recv() (*ExecInput, error)
	grpc.ServerStream
}

type orchestratorExecStreamServer struct {
	grpc.ServerStream
}

func (x *orchestratorExecStreamServer) Send(m *ExecOutput) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orchestratorExecStreamServer) Recv() (*ExecInput, error) {
	m := new(ExecInput)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Orchestrator_ValidateQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).ValidateQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_ValidateQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).ValidateQuiz(ctx, req.(*ValidateQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_WatchResources_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchResourcesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorServer).WatchResources(m, &orchestratorWatchResourcesServer{stream})
}

type Orchestrator_WatchResourcesServer interface {
	Send(*ResourceEvent) error
	grpc.ServerStream
}

type orchestratorWatchResourcesServer struct {
	grpc.ServerStream
}

func (x *orchestratorWatchResourcesServer) Send(m *ResourceEvent) error {
	return x.ServerStream.SendMsg(m)
}

// Orchestrator_ServiceDesc is the grpc.ServiceDesc for Orchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSandbox",
			Handler:    _Orchestrator_CreateSandbox_Handler,
		},
		{
			MethodName: "DestroySandbox",
			Handler:    _Orchestrator_DestroySandbox_Handler,
		},
		{
			MethodName: "GetSandboxStatus",
			Handler:    _Orchestrator_GetSandboxStatus_Handler,
		},
		{
			MethodName: "ValidateQuiz",
			Handler:    _Orchestrator_ValidateQuiz_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecStream",
			Handler:       _Orchestrator_ExecStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchResources",
			Handler:       _Orchestrator_WatchResources_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/grpc/proto/orchestrator.proto",
}
