// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/grpc/proto/orchestrator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Check_Type int32

const (
	Check_STATE    Check_Type = 0
	Check_LIVENESS Check_Type = 1
	Check_SLA      Check_Type = 2
)

// Enum value maps for Check_Type.
var (
	Check_Type_name = map[int32]string{
		0: "STATE",
		1: "LIVENESS",
		2: "SLA",
	}
	Check_Type_value = map[string]int32{
		"STATE":    0,
		"LIVENESS": 1,
		"SLA":      2,
	}
)

func (x Check_Type) Enum() *Check_Type {
	p := new(Check_Type)
	*p = x
	return p
}

func (x Check_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Check_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_proto_orchestrator_proto_enumTypes[0].Descriptor()
}

func (Check_Type) Type() protoreflect.EnumType {
	return &file_internal_grpc_proto_orchestrator_proto_enumTypes[0]
}

func (x Check_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Check_Type.Descriptor instead.
func (Check_Type) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{9, 0}
}

type CreateSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuizId        string                 `protobuf:"bytes,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	SeedManifest  string                 `protobuf:"bytes,3,opt,name=seed_manifest,json=seedManifest,proto3" json:"seed_manifest,omitempty"` // base64-encoded K8s YAML
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSandboxRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSandboxRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *CreateSandboxRequest) GetSeedManifest() string {
	if x != nil {
		return x.SeedManifest
	}
	return ""
}

type CreateSandboxResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SandboxId        string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	VclusterEndpoint string                 `protobuf:"bytes,2,opt,name=vcluster_endpoint,json=vclusterEndpoint,proto3" json:"vcluster_endpoint,omitempty"`
	Kubeconfig       string                 `protobuf:"bytes,3,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`                              // scoped kubeconfig for this sandbox
	TerminalPodIp    string                 `protobuf:"bytes,4,opt,name=terminal_pod_ip,json=terminalPodIp,proto3" json:"terminal_pod_ip,omitempty"` // IP of the ttyd shell pod for WebSocket proxy
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSandboxResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateSandboxResponse) GetVclusterEndpoint() string {
	if x != nil {
		return x.VclusterEndpoint
	}
	return ""
}

func (x *CreateSandboxResponse) GetKubeconfig() string {
	if x != nil {
		return x.Kubeconfig
	}
	return ""
}

func (x *CreateSandboxResponse) GetTerminalPodIp() string {
	if x != nil {
		return x.TerminalPodIp
	}
	return ""
}

type DestroySandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySandboxRequest) Reset() {
	*x = DestroySandboxRequest{}
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySandboxRequest) ProtoMessage() {}

func (x *DestroySandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySandboxRequest.ProtoReflect.Descriptor instead.
func (*DestroySandboxRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *DestroySandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type GetSandboxStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxStatusRequest) Reset() {
	*x = GetSandboxStatusRequest{}
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxStatusRequest) ProtoMessage() {}

func (x *GetSandboxStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *GetSandboxStatusRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type SandboxStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SandboxId        string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	State            string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // creating, ready, destroying, failed
	VclusterEndpoint string                 `protobuf:"bytes,3,opt,name=vcluster_endpoint,json=vclusterEndpoint,proto3" json:"vcluster_endpoint,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt        int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SandboxStatus) Reset() {
	*x = SandboxStatus{}
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStatus) ProtoMessage() {}

func (x *SandboxStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxStatus.ProtoReflect.Descriptor instead.
func (*SandboxStatus) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *SandboxStatus) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SandboxStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SandboxStatus) GetVclusterEndpoint() string {
	if x != nil {
		return x.VclusterEndpoint
	}
	return ""
}

func (x *SandboxStatus) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SandboxStatus) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ExecInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Stdin         []byte                 `protobuf:"bytes,2,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Resize        *TerminalResize        `protobuf:"bytes,3,opt,name=resize,proto3" json:"resize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecInput) Reset() {
	*x = ExecInput{}
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecInput) ProtoMessage() {}

func (x *ExecInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecInput.ProtoReflect.Descriptor instead.
func (*ExecInput) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *ExecInput) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ExecInput) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

func (x *ExecInput) GetResize() *TerminalResize {
	if x != nil {
		return x.Resize
	}
	return nil
}

type TerminalResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalResize) Reset() {
	*x = TerminalResize{}
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalResize) ProtoMessage() {}

func (x *TerminalResize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalResize.ProtoReflect.Descriptor instead.
func (*TerminalResize) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *TerminalResize) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *TerminalResize) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ExecOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutput) Reset() {
	*x = ExecOutput{}
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutput) ProtoMessage() {}

func (x *ExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutput.ProtoReflect.Descriptor instead.
func (*ExecOutput) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *ExecOutput) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecOutput) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

type ValidateQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	QuizId        string                 `protobuf:"bytes,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Checks        []*Check               `protobuf:"bytes,3,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateQuizRequest) Reset() {
	*x = ValidateQuizRequest{}
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateQuizRequest) ProtoMessage() {}

func (x *ValidateQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateQuizRequest.ProtoReflect.Descriptor instead.
func (*ValidateQuizRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateQuizRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ValidateQuizRequest) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *ValidateQuizRequest) GetChecks() []*Check {
	if x != nil {
		return x.Checks
	}
	return nil
}

type Check struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Check_Type             `protobuf:"varint,1,opt,name=type,proto3,enum=orchestrator.Check_Type" json:"type,omitempty"`
	SpecJson      string                 `protobuf:"bytes,2,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"` // check-type-specific config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check) Reset() {
	*x = Check{}
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *Check) GetType() Check_Type {
	if x != nil {
		return x.Type
	}
	return Check_STATE
}

func (x *Check) GetSpecJson() string {
	if x != nil {
		return x.SpecJson
	}
	return ""
}

type ValidateQuizResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passed        bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	Results       []*CheckResult         `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateQuizResponse) Reset() {
	*x = ValidateQuizResponse{}
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateQuizResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateQuizResponse) ProtoMessage() {}

func (x *ValidateQuizResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateQuizResponse.ProtoReflect.Descriptor instead.
func (*ValidateQuizResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateQuizResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *ValidateQuizResponse) GetResults() []*CheckResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ValidateQuizResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type CheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckName     string                 `protobuf:"bytes,1,opt,name=check_name,json=checkName,proto3" json:"check_name,omitempty"`
	Passed        bool                   `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Points        int32                  `protobuf:"varint,4,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{11}
}

func (x *CheckResult) GetCheckName() string {
	if x != nil {
		return x.CheckName
	}
	return ""
}

func (x *CheckResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *CheckResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckResult) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type WatchResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResourcesRequest) Reset() {
	*x = WatchResourcesRequest{}
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResourcesRequest) ProtoMessage() {}

func (x *WatchResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResourcesRequest.ProtoReflect.Descriptor instead.
func (*WatchResourcesRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{12}
}

func (x *WatchResourcesRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type ResourceEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Kind      string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // Pod, Service, Deployment, etc.
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Status    string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                        // Running, Pending, Failed, etc.
	JsonPatch string                 `protobuf:"bytes,5,opt,name=json_patch,json=jsonPatch,proto3" json:"json_patch,omitempty"` // delta update
	EventType string                 `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // Added, Modified, Deleted, Initial
	// Pod-specific fields
	ReadyContainers int32    `protobuf:"varint,7,opt,name=ready_containers,json=readyContainers,proto3" json:"ready_containers,omitempty"`
	TotalContainers int32    `protobuf:"varint,8,opt,name=total_containers,json=totalContainers,proto3" json:"total_containers,omitempty"`
	RestartCount    int32    `protobuf:"varint,9,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	Conditions      []string `protobuf:"bytes,10,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceEvent) Reset() {
	*x = ResourceEvent{}
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceEvent) ProtoMessage() {}

func (x *ResourceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceEvent.ProtoReflect.Descriptor instead.
func (*ResourceEvent) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{13}
}

func (x *ResourceEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResourceEvent) GetJsonPatch() string {
	if x != nil {
		return x.JsonPatch
	}
	return ""
}

func (x *ResourceEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ResourceEvent) GetReadyContainers() int32 {
	if x != nil {
		return x.ReadyContainers
	}
	return 0
}

func (x *ResourceEvent) GetTotalContainers() int32 {
	if x != nil {
		return x.TotalContainers
	}
	return 0
}

func (x *ResourceEvent) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *ResourceEvent) GetConditions() []string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_orchestrator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_orchestrator_proto_rawDescGZIP(), []int{14}
}

var File_internal_grpc_proto_orchestrator_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_orchestrator_proto_rawDesc = "" +
	"\n" +
	"&internal/grpc/proto/orchestrator.proto\x12\forchestrator\"m\n" +
	"\x14CreateSandboxRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\tR\x06quizId\x12#\n" +
	"\rseed_manifest\x18\x03 \x01(\tR\fseedManifest\"\xab\x01\n" +
	"\x15CreateSandboxResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12+\n" +
	"\x11vcluster_endpoint\x18\x02 \x01(\tR\x10vclusterEndpoint\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x03 \x01(\tR\n" +
	"kubeconfig\x12&\n" +
	"\x0fterminal_pod_ip\x18\x04 \x01(\tR\rterminalPodIp\"6\n" +
	"\x15DestroySandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"8\n" +
	"\x17GetSandboxStatusRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\xaf\x01\n" +
	"\rSandboxStatus\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12+\n" +
	"\x11vcluster_endpoint\x18\x03 \x01(\tR\x10vclusterEndpoint\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\"v\n" +
	"\tExecInput\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x14\n" +
	"\x05stdin\x18\x02 \x01(\fR\x05stdin\x124\n" +
	"\x06resize\x18\x03 \x01(\v2\x1c.orchestrator.TerminalResizeR\x06resize\">\n" +
	"\x0eTerminalResize\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\"<\n" +
	"\n" +
	"ExecOutput\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\fR\x06stderr\"z\n" +
	"\x13ValidateQuizRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\tR\x06quizId\x12+\n" +
	"\x06checks\x18\x03 \x03(\v2\x13.orchestrator.CheckR\x06checks\"|\n" +
	"\x05Check\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.orchestrator.Check.TypeR\x04type\x12\x1b\n" +
	"\tspec_json\x18\x02 \x01(\tR\bspecJson\"(\n" +
	"\x04Type\x12\t\n" +
	"\x05STATE\x10\x00\x12\f\n" +
	"\bLIVENESS\x10\x01\x12\a\n" +
	"\x03SLA\x10\x02\"y\n" +
	"\x14ValidateQuizResponse\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x123\n" +
	"\aresults\x18\x02 \x03(\v2\x19.orchestrator.CheckResultR\aresults\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"v\n" +
	"\vCheckResult\x12\x1d\n" +
	"\n" +
	"check_name\x18\x01 \x01(\tR\tcheckName\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06points\x18\x04 \x01(\x05R\x06points\"6\n" +
	"\x15WatchResourcesRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\xc6\x02\n" +
	"\rResourceEvent\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"json_patch\x18\x05 \x01(\tR\tjsonPatch\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\x12)\n" +
	"\x10ready_containers\x18\a \x01(\x05R\x0freadyContainers\x12)\n" +
	"\x10total_containers\x18\b \x01(\x05R\x0ftotalContainers\x12#\n" +
	"\rrestart_count\x18\t \x01(\x05R\frestartCount\x12\x1e\n" +
	"\n" +
	"conditions\x18\n" +
	" \x03(\tR\n" +
	"conditions\"\a\n" +
	"\x05Empty2\xfe\x03\n" +
	"\fOrchestrator\x12X\n" +
	"\rCreateSandbox\x12\".orchestrator.CreateSandboxRequest\x1a#.orchestrator.CreateSandboxResponse\x12J\n" +
	"\x0eDestroySandbox\x12#.orchestrator.DestroySandboxRequest\x1a\x13.orchestrator.Empty\x12V\n" +
	"\x10GetSandboxStatus\x12%.orchestrator.GetSandboxStatusRequest\x1a\x1b.orchestrator.SandboxStatus\x12C\n" +
	"\n" +
	"ExecStream\x12\x17.orchestrator.ExecInput\x1a\x18.orchestrator.ExecOutput(\x010\x01\x12U\n" +
	"\fValidateQuiz\x12!.orchestrator.ValidateQuizRequest\x1a\".orchestrator.ValidateQuizResponse\x12T\n" +
	"\x0eWatchResources\x12#.orchestrator.WatchResourcesRequest\x1a\x1b.orchestrator.ResourceEvent0\x01BQZOgithub.com/tentacle-studio/better-architecture/orchestrator/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_orchestrator_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_orchestrator_proto_rawDescData []byte
)

func file_internal_grpc_proto_orchestrator_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_orchestrator_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_orchestrator_proto_rawDesc), len(file_internal_grpc_proto_orchestrator_proto_rawDesc)))
	})
	return file_internal_grpc_proto_orchestrator_proto_rawDescData
}

var file_internal_grpc_proto_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_grpc_proto_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_grpc_proto_orchestrator_proto_goTypes = []any{
	(Check_Type)(0),                 // 0: orchestrator.Check.Type
	(*CreateSandboxRequest)(nil),    // 1: orchestrator.CreateSandboxRequest
	(*CreateSandboxResponse)(nil),   // 2: orchestrator.CreateSandboxResponse
	(*DestroySandboxRequest)(nil),   // 3: orchestrator.DestroySandboxRequest
	(*GetSandboxStatusRequest)(nil), // 4: orchestrator.GetSandboxStatusRequest
	(*SandboxStatus)(nil),           // 5: orchestrator.SandboxStatus
	(*ExecInput)(nil),               // 6: orchestrator.ExecInput
	(*TerminalResize)(nil),          // 7: orchestrator.TerminalResize
	(*ExecOutput)(nil),              // 8: orchestrator.ExecOutput
	(*ValidateQuizRequest)(nil),     // 9: orchestrator.ValidateQuizRequest
	(*Check)(nil),                   // 10: orchestrator.Check
	(*ValidateQuizResponse)(nil),    // 11: orchestrator.ValidateQuizResponse
	(*CheckResult)(nil),             // 12: orchestrator.CheckResult
	(*WatchResourcesRequest)(nil),   // 13: orchestrator.WatchResourcesRequest
	(*ResourceEvent)(nil),           // 14: orchestrator.ResourceEvent
	(*Empty)(nil),                   // 15: orchestrator.Empty
}
var file_internal_grpc_proto_orchestrator_proto_depIdxs = []int32{
	7,  // 0: orchestrator.ExecInput.resize:type_name -> orchestrator.TerminalResize
	10, // 1: orchestrator.ValidateQuizRequest.checks:type_name -> orchestrator.Check
	0,  // 2: orchestrator.Check.type:type_name -> orchestrator.Check.Type
	12, // 3: orchestrator.ValidateQuizResponse.results:type_name -> orchestrator.CheckResult
	1,  // 4: orchestrator.Orchestrator.CreateSandbox:input_type -> orchestrator.CreateSandboxRequest
	3,  // 5: orchestrator.Orchestrator.DestroySandbox:input_type -> orchestrator.DestroySandboxRequest
	4,  // 6: orchestrator.Orchestrator.GetSandboxStatus:input_type -> orchestrator.GetSandboxStatusRequest
	6,  // 7: orchestrator.Orchestrator.ExecStream:input_type -> orchestrator.ExecInput
	9,  // 8: orchestrator.Orchestrator.ValidateQuiz:input_type -> orchestrator.ValidateQuizRequest
	13, // 9: orchestrator.Orchestrator.WatchResources:input_type -> orchestrator.WatchResourcesRequest
	2,  // 10: orchestrator.Orchestrator.CreateSandbox:output_type -> orchestrator.CreateSandboxResponse
	15, // 11: orchestrator.Orchestrator.DestroySandbox:output_type -> orchestrator.Empty
	5,  // 12: orchestrator.Orchestrator.GetSandboxStatus:output_type -> orchestrator.SandboxStatus
	8,  // 13: orchestrator.Orchestrator.ExecStream:output_type -> orchestrator.ExecOutput
	11, // 14: orchestrator.Orchestrator.ValidateQuiz:output_type -> orchestrator.ValidateQuizResponse
	14, // 15: orchestrator.Orchestrator.WatchResources:output_type -> orchestrator.ResourceEvent
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_orchestrator_proto_init() }
func file_internal_grpc_proto_orchestrator_proto_init() {
	if File_internal_grpc_proto_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_orchestrator_proto_rawDesc), len(file_internal_grpc_proto_orchestrator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_orchestrator_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_orchestrator_proto_depIdxs,
		EnumInfos:         file_internal_grpc_proto_orchestrator_proto_enumTypes,
		MessageInfos:      file_internal_grpc_proto_orchestrator_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_orchestrator_proto = out.File
	file_internal_grpc_proto_orchestrator_proto_goTypes = nil
	file_internal_grpc_proto_orchestrator_proto_depIdxs = nil
}
