// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: internal/grpc/proto/orchestrator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Orchestrator_CreateSandbox_FullMethodName    = "/orchestrator.Orchestrator/CreateSandbox"
	Orchestrator_DestroySandbox_FullMethodName   = "/orchestrator.Orchestrator/DestroySandbox"
	Orchestrator_GetSandboxStatus_FullMethodName = "/orchestrator.Orchestrator/GetSandboxStatus"
	Orchestrator_ExecStream_FullMethodName       = "/orchestrator.Orchestrator/ExecStream"
	Orchestrator_ValidateQuiz_FullMethodName     = "/orchestrator.Orchestrator/ValidateQuiz"
	Orchestrator_WatchResources_FullMethodName   = "/orchestrator.Orchestrator/WatchResources"
)

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorClient interface {
	// Sandbox lifecycle
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error)
	DestroySandbox(ctx context.Context, in *DestroySandboxRequest, opts ...grpc.CallOption) (*Empty, error)
	GetSandboxStatus(ctx context.Context, in *GetSandboxStatusRequest, opts ...grpc.CallOption) (*SandboxStatus, error)
	// Terminal exec — bidirectional stream
	ExecStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecInput, ExecOutput], error)
	// Validation
	ValidateQuiz(ctx context.Context, in *ValidateQuizRequest, opts ...grpc.CallOption) (*ValidateQuizResponse, error)
	// Sandbox resource state — server-side stream for real-time updates
	WatchResources(ctx context.Context, in *WatchResourcesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResourceEvent], error)
}

type orchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorClient(cc grpc.ClientConnInterface) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSandboxResponse)
	err := c.cc.Invoke(ctx, Orchestrator_CreateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) DestroySandbox(ctx context.Context, in *DestroySandboxRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Orchestrator_DestroySandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) GetSandboxStatus(ctx context.Context, in *GetSandboxStatusRequest, opts ...grpc.CallOption) (*SandboxStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxStatus)
	err := c.cc.Invoke(ctx, Orchestrator_GetSandboxStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) ExecStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecInput, ExecOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Orchestrator_ServiceDesc.Streams[0], Orchestrator_ExecStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecInput, ExecOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_ExecStreamClient = grpc.BidiStreamingClient[ExecInput, ExecOutput]

func (c *orchestratorClient) ValidateQuiz(ctx context.Context, in *ValidateQuizRequest, opts ...grpc.CallOption) (*ValidateQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateQuizResponse)
	err := c.cc.Invoke(ctx, Orchestrator_ValidateQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) WatchResources(ctx context.Context, in *WatchResourcesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResourceEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Orchestrator_ServiceDesc.Streams[1], Orchestrator_WatchResources_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchResourcesRequest, ResourceEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_WatchResourcesClient = grpc.ServerStreamingClient[ResourceEvent]

// OrchestratorServer is the server API for Orchestrator service.
// All implementations must embed UnimplementedOrchestratorServer
// for forward compatibility.
type OrchestratorServer interface {
	// Sandbox lifecycle
	CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error)
	DestroySandbox(context.Context, *DestroySandboxRequest) (*Empty, error)
	GetSandboxStatus(context.Context, *GetSandboxStatusRequest) (*SandboxStatus, error)
	// Terminal exec — bidirectional stream
	ExecStream(grpc.BidiStreamingServer[ExecInput, ExecOutput]) error
	// Validation
	ValidateQuiz(context.Context, *ValidateQuizRequest) (*ValidateQuizResponse, error)
	// Sandbox resource state — server-side stream for real-time updates
	WatchResources(*WatchResourcesRequest, grpc.ServerStreamingServer[ResourceEvent]) error
	mustEmbedUnimplementedOrchestratorServer()
}

// UnimplementedOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServer struct{}

func (UnimplementedOrchestratorServer) CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedOrchestratorServer) DestroySandbox(context.Context, *DestroySandboxRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroySandbox not implemented")
}
func (UnimplementedOrchestratorServer) GetSandboxStatus(context.Context, *GetSandboxStatusRequest) (*SandboxStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandboxStatus not implemented")
}
func (UnimplementedOrchestratorServer) ExecStream(grpc.BidiStreamingServer[ExecInput, ExecOutput]) error {
	return status.Error(codes.Unimplemented, "method ExecStream not implemented")
}
func (UnimplementedOrchestratorServer) ValidateQuiz(context.Context, *ValidateQuizRequest) (*ValidateQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateQuiz not implemented")
}
func (UnimplementedOrchestratorServer) WatchResources(*WatchResourcesRequest, grpc.ServerStreamingServer[ResourceEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchResources not implemented")
}
func (UnimplementedOrchestratorServer) mustEmbedUnimplementedOrchestratorServer() {}
func (UnimplementedOrchestratorServer) testEmbeddedByValue()                      {}

// UnsafeOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServer will
// result in compilation errors.
type UnsafeOrchestratorServer interface {
	mustEmbedUnimplementedOrchestratorServer()
}

func RegisterOrchestratorServer(s grpc.ServiceRegistrar, srv OrchestratorServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Orchestrator_ServiceDesc, srv)
}

func _Orchestrator_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_DestroySandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).DestroySandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_DestroySandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).DestroySandbox(ctx, req.(*DestroySandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_GetSandboxStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetSandboxStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_GetSandboxStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetSandboxStatus(ctx, req.(*GetSandboxStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_ExecStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrchestratorServer).ExecStream(&grpc.GenericServerStream[ExecInput, ExecOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_ExecStreamServer = grpc.BidiStreamingServer[ExecInput, ExecOutput]

func _Orchestrator_ValidateQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).ValidateQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_ValidateQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).ValidateQuiz(ctx, req.(*ValidateQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_WatchResources_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchResourcesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorServer).WatchResources(m, &grpc.GenericServerStream[WatchResourcesRequest, ResourceEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orchestrator_WatchResourcesServer = grpc.ServerStreamingServer[ResourceEvent]

// Orchestrator_ServiceDesc is the grpc.ServiceDesc for Orchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSandbox",
			Handler:    _Orchestrator_CreateSandbox_Handler,
		},
		{
			MethodName: "DestroySandbox",
			Handler:    _Orchestrator_DestroySandbox_Handler,
		},
		{
			MethodName: "GetSandboxStatus",
			Handler:    _Orchestrator_GetSandboxStatus_Handler,
		},
		{
			MethodName: "ValidateQuiz",
			Handler:    _Orchestrator_ValidateQuiz_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecStream",
			Handler:       _Orchestrator_ExecStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchResources",
			Handler:       _Orchestrator_WatchResources_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/grpc/proto/orchestrator.proto",
}
